---
title: "student_enrollment"
author: "John Park"
date: "7/23/2019"
output: github_document
editor_options: 
  chunk_output_type: inline
---
## Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	fig.showtext = T
)
```
```{r}
font_add_google("Roboto Condensed", "roboto")
showtext_auto()
tol12 <- PerformanceAnalytics::tol12qualitative
```
```{r}
source(here("_utils/edsight_functions.R"))
nh_dists <- school_dists %>% 
  dplyr::filter(region %in% c("New Haven Inner Ring", "New Haven Outer Ring")) %>% 
  rbind(c("New Haven Inner Ring", "New Haven"))
nh_dists$district <- nh_dists$district %>%
  paste("School District")

names <- c("1718", "1617", 
           "1516", "1415", 
           "1314", "1213", 
           "1112", "1011")
```

## Student enrollment by race
```{r}
df1 <- map_dfr (names, function(name) { 
  readRDS(here("ctsde/outputs", str_glue("enrollment_race_{name}.rds")))
  }
)

df1 <- df1 %>% 
  as_tibble() %>% 
  
  mutate_at('Value', as.numeric) %>% 
  na_if(-9999) %>% 
  mutate_all(funs(ifelse(is.na(.), 0, .))) %>% 
  
  dplyr::filter(.$'District' %in% nh_dists$'district') %>% 
  rename('district' = "District") %>% 
  right_join(nh_dists, by = 'district') %>% 
  
  # create, student white count, student total count, percent minority
  group_by(district, Year) %>% 
  mutate(student_total_count = sum(Value)) %>% 
  ungroup() %>% 
  dplyr::filter(`Race/Ethnicity` == "White") %>% 
  rename(student_white_count = Value) %>% 
  mutate(student_perc_minority = 100*(1-student_white_count/student_total_count)) %>% 
  
  # convert year to numeric
  rename('year' = 'Year') %>% 
  mutate_at('year', str_sub, start=1, end=4) %>% 
  mutate_at('year', as.numeric) %>% 
  
  select(region, district, year, student_white_count, student_total_count, student_perc_minority)

# Create and bind Greater New Haven row
gnh1 <- df1 %>% 
  group_by(year) %>% 
  summarise_each(funs(sum), student_white_count, student_total_count) %>% 
  ungroup() %>% 
  mutate(region = "NA", district = "Greater New Haven") %>% 
  mutate(student_perc_minority = 100*(1-student_white_count/student_total_count)) %>% 
  select(region, district, year, student_white_count, student_total_count, student_perc_minority)

df1 <- df1 %>% bind_rows(gnh1) %>% 
    mutate_at("district", str_remove, " School District") # remove 'School District'
```

## Staffing by race
```{r}
df2 <- map_dfr (names, function(name) { 
  read_csv(here("edsight/raw_data", str_glue("StaffingRace_{name}.csv")), skip = 2, col_types = "ccccc") %>% 
    mutate(year = name)
  }
  )

df2 <- df2 %>%
  select(District, School, year, Race, Count) %>% 
  mutate_at(c("District", "School"), na.locf) %>% 
  sapply(gsub, pattern = "=", rep = "") %>% 
  as_tibble %>% 
  sapply(gsub, pattern = '"', rep = "") %>% 
  as_tibble %>% 
  na_if(".") %>% 
  drop_na %>% 
  mutate_at(c('Count'), as.numeric) %>% 
  mutate_all(funs(ifelse(is.na(.), 0, .))) %>% 
  
  dplyr::filter(.$'District' %in% nh_dists$'district') %>% 
  rename('district' = "District") %>% 
  right_join(nh_dists, by = 'district') %>% 
  
  # convert year to numeric
  mutate_at('year', str_sub, start=1, end=2) %>% 
  mutate_at('year', paste0, "20", .) %>% 
  mutate_at('year', as.numeric) %>% 

  # create, staff white count, staff total count, and percent white staff
  group_by(district, year) %>% 
  mutate(staff_total_count = sum(Count)) %>% 
  dplyr::filter(`Race` == "White") %>%
  mutate(staff_white_count = sum(Count)) %>% 
  ungroup() %>% 
  mutate(staff_perc_minority = 100*(1-staff_white_count/staff_total_count)) %>% 
  select(region, district, year, staff_white_count, staff_total_count, staff_perc_minority) %>% 
  distinct()

# Create and bind Greater New Haven row
gnh2 <- df2 %>% 
  group_by(year) %>% 
  summarise_each(funs(sum), staff_white_count, staff_total_count) %>% 
  ungroup() %>% 
  mutate(region = "NA", district = "Greater New Haven") %>% 
  mutate(staff_perc_minority = 100*(1-staff_white_count/staff_total_count)) %>% 
  select(region, district, year, staff_white_count, staff_total_count, staff_perc_minority)

df2 <- df2 %>% bind_rows(gnh2) %>% 
  mutate_at("district", str_remove, " School District") # remove 'School District'
```

## Join student and staff data
```{r}
df <- df1 %>%
  bind_cols(df2) %>% 
  select(region, district, year, student_white_count, staff_white_count, student_total_count, staff_total_count) %>% 
  
  # make long
  gather(white_type, white_count, c(student_white_count, staff_white_count)) %>% 
  mutate_at("white_type", str_replace, pattern = "_white_count", replacement = "") %>%
  gather(total_type, total_count, c(student_total_count, staff_total_count)) %>% 
  mutate_at("total_type", str_replace, pattern = "_total_count", replacement = "") %>% 
  filter((white_type == "student" & total_type == "student") | (white_type == "staff" & total_type == "staff")) %>% 
  
  # white_type and total_type are redundant now
  rename(type = white_type) %>% 
  select(-total_type) %>% 

  # clean
  mutate_at("district", str_replace, pattern = " School District", replacement = "") %>% 
  mutate_at("region", str_replace, pattern = "New Haven ", replacement = "") %>% 

  # calculate percent minority (again)
  mutate(perc_minority = 100*(1-white_count/total_count))
```


## Charts
```{r}
df1_inner <- df1 %>% 
  filter(region == "New Haven Inner Ring")
df1_inner %>% 
  ggplot(aes(x = year, y = student_perc_minority, group = district, color = tol12[9])) + 
    geom_line() +
    geom_point(data = subset(df1_inner, year == 2010 | year == 2017)) +
    scale_colour_discrete(guide = 'none') +
    geom_dl(aes(label = district), method = list(dl.trans(x = x + 0.2), dl.combine("last.bumpup"), cex = 0.8)) +
    theme_din(xgrid = T, ygrid = "dotted") +
      labs(title = "Inner Ring Student Diversity has been increasing, 2010-2017", 
           y = "Percent student minority",
           x = "Year",
           caption = "Data from EdSight (CSDE)") +
    xlim(2010, 2018)

df1_outer <- df1 %>% 
  filter(region == "New Haven Outer Ring")
df1_outer %>% 
  ggplot(aes(x = year, y = student_perc_minority, group = district, color = tol12[1])) + 
    geom_line() +
    geom_point(data = subset(df1_outer, year == 2010 | year == 2017)) +
    scale_colour_discrete(guide = 'none') +
    geom_dl(aes(label = district), method = list(dl.trans(x = x + 0.2), dl.combine("last.bumpup"), cex = 0.8)) +
    theme_din(xgrid = T, ygrid = "dotted") +
      labs(title = "Outer Ring Student Diversity has been increasing, 2010-2017", 
           y = "Percent student minority",
           x = "Year",
           caption = "Data from EdSight (CSDE)") +
    xlim(2010, 2018)
```

```{r}
df2 %>% ggplot(aes(x = year, y = staff_perc_minority, group = district)) +
  geom_line(aes(color = district)) +
  theme(axis.text.x = element_text(angle = 20, hjust = 1))
df2_inner <- df2 %>% 
  filter(region == "New Haven Inner Ring")
df2_inner %>% 
  ggplot(aes(x = year, y = staff_perc_minority, group = district, color = tol12[3])) + 
    geom_line() +
    geom_point(data = subset(df2_inner, year == 2010 | year == 2017)) +
    scale_colour_discrete(guide = 'none') +
    geom_dl(aes(label = district), method = list(dl.trans(x = x + 0.2), dl.combine("last.bumpup"), cex = 0.8)) +
    theme_din(xgrid = T, ygrid = "dotted") +
      labs(title = "Inner Ring Staff Diversity has been stagnant, 2010-2017", 
           y = "Percent student minority",
           x = "Year",
           caption = "Data from EdSight (CSDE)") +
    xlim(2010, 2018)

df1_outer <- df1 %>% 
  filter(region == "New Haven Outer Ring")
df1_outer %>% 
  ggplot(aes(x = year, y = student_perc_minority, group = district, color = tol12[1])) + 
    geom_line() +
    geom_point(data = subset(df1_outer, year == 2010 | year == 2017)) +
    scale_colour_discrete(guide = 'none') +
    geom_dl(aes(label = district), method = list(dl.trans(x = x + 0.2), dl.combine("last.bumpup"), cex = 0.8)) +
    theme_din(xgrid = T, ygrid = "dotted") +
      labs(title = "Outer Ring Student Diversity has been increasing, 2010-2017", 
           y = "Percent student minority",
           x = "Year",
           caption = "Data from EdSight (CSDE)") +
    xlim(2010, 2018)
```

```{r}
df %>% 
  filter(year == 2017) %>% 
  ggplot(aes(x=district, y=perc_minority, fill=type)) + 
  geom_bar(stat="identity", position=position_dodge()) +
  theme(axis.text.x = element_text(angle = 20, hjust = 1)) +
  labs(title = "Percent Minority Staff and Students by District, 2017",
       x = "District",
       y = "Percent Minority",
       caption =" Enrollment and staffing data from EdSight (CSDE)")
```
